# Generated by Django 2.2.5 on 2022-04-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20220417_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
